"""add slug description image_url to tokens

Revision ID: 9cd097779a53
Revises: 002
Create Date: 2026-03-01 20:00:18.859325
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers
revision: str = '9cd097779a53'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('contributions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_contributions_user_sale'), table_name='contributions')
    op.create_index(op.f('ix_contributions_id'), 'contributions', ['id'], unique=False)
    op.alter_column('issuers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_issuers_id'), 'issuers', ['id'], unique=False)
    op.alter_column('kyc_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_kyc_applications_id'), 'kyc_applications', ['id'], unique=False)
    op.alter_column('redemption_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_redemption_requests_id'), 'redemption_requests', ['id'], unique=False)
    op.alter_column('sale_phases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_sale_phases_id'), 'sale_phases', ['id'], unique=False)
    op.alter_column('token_sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_token_sales_id'), 'token_sales', ['id'], unique=False)
    op.add_column('tokens', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('tokens', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('tokens', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_slug'), 'tokens', ['slug'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('vesting_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_vesting_user_token'), table_name='vesting_schedules')
    op.create_index(op.f('ix_vesting_schedules_id'), 'vesting_schedules', ['id'], unique=False)
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_vesting_schedules_id'), table_name='vesting_schedules')
    op.create_index(op.f('ix_vesting_user_token'), 'vesting_schedules', ['user_id', 'token_id'], unique=False)
    op.alter_column('vesting_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tokens_slug'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.alter_column('tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_column('tokens', 'image_url')
    op.drop_column('tokens', 'description')
    op.drop_column('tokens', 'slug')
    op.drop_index(op.f('ix_token_sales_id'), table_name='token_sales')
    op.alter_column('token_sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_sale_phases_id'), table_name='sale_phases')
    op.alter_column('sale_phases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_redemption_requests_id'), table_name='redemption_requests')
    op.alter_column('redemption_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_kyc_applications_id'), table_name='kyc_applications')
    op.alter_column('kyc_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_issuers_id'), table_name='issuers')
    op.alter_column('issuers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_contributions_id'), table_name='contributions')
    op.create_index(op.f('ix_contributions_user_sale'), 'contributions', ['user_id', 'sale_id'], unique=False)
    op.alter_column('contributions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
