/**
 * Map Sale.sol and IssuerOTCToken.sol custom-error 4-byte selectors to
 * user-friendly messages. viem reports custom errors as the selector hex,
 * so substring matching alone misses them.
 *
 * Selectors generated by `keccak256(errorSig)[0:4]`. See
 * `contracts/src/sale/Sale.sol` and `contracts/src/otc/IssuerOTCToken.sol`.
 */
export const CUSTOM_ERROR_SELECTORS: Record<string, string> = {
  // ── Sale.sol ────────────────────────────────────────────────────
  "0xf525e320": "Sale status does not allow this action.",
  "0x7bfa4b9f": "Caller is not an admin.",
  "0x54ec5063": "Caller is not the issuer.",
  "0x7f41f221": "Caller is not the issuer or an admin.",
  "0xd92e233d": "Zero address is not allowed.",
  "0x969bf728": "Nothing to claim.",
  "0x646cf558": "You have already claimed your tokens for this sale.",
  "0xf5d65a75": "Use the vault claim flow for this sale.",
  "0x9a36fd9c": "Invalid sale phase.",
  "0xf2469089": "This sale phase has not started yet.",
  "0x663505c8": "This sale phase has ended.",
  "0x8875a799": "Amount is below the minimum contribution for this phase.",
  "0x0cb363f2": "Amount exceeds the maximum contribution per investor.",
  "0x45939939": "This contribution would exceed the sale's hard cap.",
  "0x38ad1bbd": "Exceeds the per-block contribution limit. Split into smaller transactions and try again.",
  "0x83855724": "Your wallet is not KYC-verified. Please complete identity verification first.",
  "0x584a7938": "Your wallet is not whitelisted for this sale phase.",
  "0x8541190c": "This phase's token allocation is fully subscribed.",
  "0x13ce5d74": "Cannot add a phase at this time.",
  "0xbf48e85d": "Min contribution must be greater than zero. Set a non-zero minimum (e.g. $1).",
  "0x58c93530": "Per-block limit must be greater than zero.",
  // Sale init / phase validation (round 4) — Sale.sol + CiretaVault.sol
  "0x5c9e11e8": "Soft cap and hard cap must both be greater than zero, and soft cap cannot exceed hard cap.",
  "0x8bff87cf": "Platform fee cannot exceed 10% (1000 basis points).",
  "0x5e977042": "Sale window is invalid: start must be before end, and end must be in the future.",
  "0x6e610074": "Phase price per token must be greater than zero.",
  "0x09343c3e": "Phase start time must be before its end time.",
  "0x6f9a354b": "Phase start/end must fall inside the sale window.",
  "0x56c3964d": "Phase end time must be in the future.",
  "0x205be542": "Phase max contribution must be greater than or equal to min contribution.",
  "0xe25a5543": "Phase allocation must be greater than zero (phase-allocated sale).",
  "0x646bd99d": "Sum of phase allocations exceeds the sale's hard cap.",
  "0x5c9504c2": "Vesting config is invalid: cliff must be strictly less than total vesting duration.",
  // Sale init / ops + token amount checks (round 4 part 2)
  "0xaf5716a6": "Issuer wallet must be KYC-verified on the identity registry before deploying a sale.",
  "0x2c1b7dae": "Vault has no project tokens deposited — cannot finalize a vested sale with an empty vault.",
  "0x6a5b6ddc": "Per-block contribution limit must be at least 1 USDC (1e6).",
  "0x1f2a2005": "Token amount must be greater than zero.",
  "0xb7b24097": "Sale is not active.",
  "0xeda53895": "Investor is not verified for this sale.",
  "0x98a6eccc": "Sale cannot be finalized yet.",
  "0xcd28344a": "OTC payment is not enabled for this sale.",
  "0xd0d04f60": "Nothing to withdraw.",
  "0x7752c4a0": "Sale has not been finalized yet.",
  "0x21e3ff2d": "Sale tokens have not been deposited yet.",
  "0x27836e1f": "Time delay has not yet elapsed.",
  // ── IssuerOTCToken.sol ─────────────────────────────────────────
  "0xa3e9d91e": "OTC token recipient is not on the identity registry. The sale contract may not be whitelisted yet — contact support.",
  // ── Round-5 — sale + phase + refund + ERC-1155 fraction errors ──
  "0xea913584": "Phase overlaps with another phase. Choose non-overlapping start/end times.",
  "0xcbe28a93": "Cannot extend a phase that has already ended.",
  "0xe4965da3": "New end time must be later than the current end time.",
  "0x5ef7c526": "Phase extension would overlap with the next phase.",
  "0x87240838": "Top-up minimum must be at least 1000 USDC (contract floor).",
  "0xf1ea44a0": "Amount is below the top-up minimum for repeat buyers in this phase.",
  "0xcf56e448": "A phase is currently active — wait until it ends before closing.",
  "0xc19f17a9": "Sale has not been approved by an admin yet.",
  "0xf82cae11": "Refunds are not yet active. Issuer or admin must activate them first.",
  "0x4c442bdf": "You are not eligible for an on-chain refund. OTC contributors get refunded off-chain.",
  "0xc2f5625a": "Amount is too small to allocate any tokens.",
  "0xfd43402b": "Insufficient OTC token balance.",
  "0x7af54dad": "OTC token spending allowance is too low. Re-approve before buying.",
  "0xc919b2f2": "Total token supply must be greater than zero.",
  "0x1c07ee3d": "Buy would exceed the sale's total token supply.",
  "0x9cbe2357": "Fraction tokens are non-transferable (soul-bound).",
  "0xdfa1a408": "Invalid fraction token id (must be 1 for USDC or 2 for OTC).",
  "0x101f817a": "Sale or refunds are already in the requested state.",
};

/**
 * Map common revert string fragments (legacy require-string reverts) to
 * friendlier messages. Custom-error selectors take priority over these.
 */
export const REVERT_STRING_FRAGMENTS: Record<string, string> = {
  "kyc required": "Your wallet is not KYC-verified. Please complete identity verification first.",
  "not whitelisted": "Your wallet is not whitelisted for this sale phase.",
  "below min": "Amount is below the minimum contribution for this phase.",
  "exceeds max": "Amount exceeds the maximum contribution limit.",
  "exceeds hard cap": "This contribution would exceed the sale's hard cap.",
  "phase not started": "This sale phase has not started yet.",
  "phase ended": "This sale phase has ended.",
  "exceeds allocation": "This phase's token allocation is fully subscribed.",
  "exceeds block limit": "Exceeds the per-block contribution limit. Split into smaller transactions and try again.",
  "invalid phase": "Invalid sale phase.",
  "insufficient otc token balance": "You don't have enough OTC tokens for this purchase.",
  "otc token not approved": "OTC token spending allowance is too low. Please re-approve.",
  "amount must be > 0": "Amount must be greater than zero.",
  "amount too small for token allocation": "Amount is too small to allocate any tokens.",
};

/**
 * Parse a wagmi/viem error and return a friendly message.
 *
 * Tries (in order):
 * 1. Custom-error selector match (e.g. `0xa3e9d91e` → `RecipientNotVerified`)
 * 2. Revert-string fragment match (legacy `require()` reverts)
 * 3. Wallet-side errors (user rejected, insufficient funds)
 * 4. Generic fallback
 */
export function parseRevertReason(error: unknown): string {
  if (!error) return "Transaction failed. Please try again.";

  // Drill into viem-style nested errors to find the data field
  let current: unknown = error;
  let selector: string | null = null;
  for (let i = 0; i < 6 && current; i++) {
    if (typeof current === "object" && current !== null) {
      const obj = current as { data?: unknown; cause?: unknown; message?: unknown };
      if (typeof obj.data === "string" && obj.data.startsWith("0x") && obj.data.length >= 10) {
        selector = obj.data.slice(0, 10).toLowerCase();
        break;
      }
      current = obj.cause;
    } else {
      break;
    }
  }

  // Also scan the message string for a 0x... selector (viem sometimes embeds it there)
  const msg = error instanceof Error ? error.message : String(error);
  if (!selector) {
    const m = msg.match(/0x[a-fA-F0-9]{8}/);
    if (m) selector = m[0].toLowerCase();
  }

  if (selector) {
    const friendly = CUSTOM_ERROR_SELECTORS[selector];
    if (friendly) return friendly;
  }

  // Wallet-side
  if (msg.includes("User rejected") || msg.includes("user rejected") || msg.includes("User denied")) {
    return "Transaction was rejected in your wallet.";
  }
  if (msg.toLowerCase().includes("insufficient funds")) {
    return "Insufficient ETH for gas. Please top up your wallet.";
  }

  // Legacy require-string fragments
  const lower = msg.toLowerCase();
  for (const [frag, friendly] of Object.entries(REVERT_STRING_FRAGMENTS)) {
    if (lower.includes(frag)) return friendly;
  }

  return "Transaction failed. Please try again.";
}
