/**
 * CiretaToken ABI — ERC-3643 security token.
 * Source: contracts/src/token/CiretaToken.sol
 */
export const CIRETA_TOKEN_ABI = [
  { name: "mint", type: "function", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "burn", type: "function", stateMutability: "nonpayable", inputs: [{ name: "account", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "transfer", type: "function", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { name: "approve", type: "function", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { name: "balanceOf", type: "function", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "allowance", type: "function", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "name", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { name: "symbol", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { name: "decimals", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { name: "totalSupply", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "identityRegistry", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "compliance", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "paused", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { name: "pause", type: "function", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { name: "unpause", type: "function", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { name: "setAddressFrozen", type: "function", stateMutability: "nonpayable", inputs: [{ name: "addr", type: "address" }, { name: "freeze", type: "bool" }], outputs: [] },
  { name: "forcedTransfer", type: "function", stateMutability: "nonpayable", inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "recoveryAddress", type: "function", stateMutability: "nonpayable", inputs: [{ name: "lostWallet", type: "address" }, { name: "newWallet", type: "address" }, { name: "investorOnchainID", type: "address" }], outputs: [] },
  { name: "isFrozen", type: "function", stateMutability: "view", inputs: [{ name: "addr", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { name: "freezePartialTokens", type: "function", stateMutability: "nonpayable", inputs: [{ name: "addr", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "unfreezePartialTokens", type: "function", stateMutability: "nonpayable", inputs: [{ name: "addr", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "getFrozenTokens", type: "function", stateMutability: "view", inputs: [{ name: "addr", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "batchMint", type: "function", stateMutability: "nonpayable", inputs: [{ name: "toList", type: "address[]" }, { name: "amounts", type: "uint256[]" }], outputs: [] },
  { name: "batchBurn", type: "function", stateMutability: "nonpayable", inputs: [{ name: "fromList", type: "address[]" }, { name: "amounts", type: "uint256[]" }], outputs: [] },
  { name: "batchSetAddressFrozen", type: "function", stateMutability: "nonpayable", inputs: [{ name: "addrList", type: "address[]" }, { name: "freezeList", type: "bool[]" }], outputs: [] },
  { name: "batchFreezePartialTokens", type: "function", stateMutability: "nonpayable", inputs: [{ name: "addrList", type: "address[]" }, { name: "amounts", type: "uint256[]" }], outputs: [] },
  { name: "batchUnfreezePartialTokens", type: "function", stateMutability: "nonpayable", inputs: [{ name: "addrList", type: "address[]" }, { name: "amounts", type: "uint256[]" }], outputs: [] },
  { name: "batchForcedTransfer", type: "function", stateMutability: "nonpayable", inputs: [{ name: "fromList", type: "address[]" }, { name: "toList", type: "address[]" }, { name: "amounts", type: "uint256[]" }], outputs: [] },
  { name: "batchTransfer", type: "function", stateMutability: "nonpayable", inputs: [{ name: "toList", type: "address[]" }, { name: "amounts", type: "uint256[]" }], outputs: [] },
] as const;
