/**
 * Sale contract ABI — subset for admin/issuer portal interactions.
 *
 * Source: contracts/src/sale/Sale.sol (round 5)
 */
export const SALE_ABI = [
  {
    name: "initialize",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_token", type: "address" },
      { name: "_paymentToken", type: "address" },
      { name: "_identityRegistry", type: "address" },
      { name: "_issuer", type: "address" },
      { name: "_factory", type: "address" },
      { name: "_feeManager", type: "address" },
      { name: "_softCap", type: "uint256" },
      { name: "_hardCap", type: "uint256" },
      { name: "_feeBasisPoints", type: "uint256" },
      { name: "_feeCapUsdc", type: "uint256" },
      { name: "_otcToken", type: "address" },
      { name: "_saleStartTime", type: "uint256" },
      { name: "_saleEndTime", type: "uint256" },
      { name: "_totalTokenSupply", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "activate",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "approveSale",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "unapproveSale",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "addPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "pricePerToken", type: "uint256" },
      { name: "allocation", type: "uint256" },
      { name: "minTokens", type: "uint256" },
      { name: "maxTokens", type: "uint256" },
      { name: "topUpMinTokens", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "whitelistOnly", type: "bool" },
      { name: "allocationMode", type: "uint8" },
    ],
    outputs: [],
  },
  {
    name: "extendPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "phaseId", type: "uint256" },
      { name: "newEndTime", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "shortenPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "phaseId", type: "uint256" },
      { name: "newEndTime", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "advancePhaseStart",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "phaseId", type: "uint256" },
      { name: "newStartTime", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "getRemainingSupply",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "setWhitelist",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "phaseId", type: "uint256" },
      { name: "addresses", type: "address[]" },
      { name: "allow", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "finalizeSale",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "closeSale",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "failed", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "activateRefunds",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "pause",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "unpause",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "reject",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "emergencyWithdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "withdrawFunds",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "withdrawTokens",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "depositProjectTokens",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "setOTCToken",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_otcToken", type: "address" }],
    outputs: [],
  },
  // View functions
  { name: "status", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { name: "totalRaised", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "totalTokenSold", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "totalTokenSupply", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "issuer", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "factory", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "vault", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "fractionToken", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "saleMode", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { name: "feeBasisPoints", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "otcToken", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "openEnded", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { name: "approved", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { name: "finalizationPending", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { name: "refundsActive", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { name: "version", type: "function", stateMutability: "pure", inputs: [], outputs: [{ name: "", type: "string" }] },
  { name: "upgradeNonce", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "getPhaseCount", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  {
    name: "getPhase",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "phaseId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "pricePerToken", type: "uint256" },
          { name: "allocation", type: "uint256" },
          { name: "sold", type: "uint256" },
          { name: "minTokens", type: "uint256" },
          { name: "maxTokens", type: "uint256" },
          { name: "topUpMinTokens", type: "uint256" },
          { name: "startTime", type: "uint256" },
          { name: "endTime", type: "uint256" },
          { name: "whitelistOnly", type: "bool" },
          { name: "allocationMode", type: "uint8" },
        ],
      },
    ],
  },
  // Events
  { name: "SaleStatusChanged", type: "event", inputs: [{ name: "newStatus", type: "uint8", indexed: false }] },
  { name: "SaleApproved", type: "event", inputs: [] },
  { name: "SaleUnapproved", type: "event", inputs: [] },
  { name: "PhaseExtended", type: "event", inputs: [{ name: "phaseId", type: "uint256", indexed: true }, { name: "newEndTime", type: "uint256", indexed: false }] },
  { name: "FinalizationPending", type: "event", inputs: [{ name: "totalRaised", type: "uint256", indexed: false }, { name: "totalTokenSold", type: "uint256", indexed: false }] },
  { name: "RefundsActivated", type: "event", inputs: [] },
  { name: "SaleClosed", type: "event", inputs: [{ name: "failed", type: "bool", indexed: false }, { name: "closer", type: "address", indexed: false }] },
] as const;
