/**
 * Sale contract ABI — subset for admin/issuer portal interactions.
 *
 * Source: contracts/src/sale/Sale.sol
 */
export const SALE_ABI = [
  {
    name: "initialize",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_token", type: "address" },
      { name: "_paymentToken", type: "address" },
      { name: "_identityRegistry", type: "address" },
      { name: "_issuer", type: "address" },
      { name: "_factory", type: "address" },
      { name: "_feeManager", type: "address" },
      { name: "_softCap", type: "uint256" },
      { name: "_hardCap", type: "uint256" },
      { name: "_feeBasisPoints", type: "uint256" },
      { name: "_feeCapUsdc", type: "uint256" },
      { name: "_otcToken", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "activate",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "addPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "pricePerToken", type: "uint256" },
      { name: "allocation", type: "uint256" },
      { name: "minContribution", type: "uint256" },
      { name: "maxContribution", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "whitelistOnly", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "setWhitelist",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "phaseId", type: "uint256" },
      { name: "addresses", type: "address[]" },
      { name: "allow", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "finalizeSale",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "pause",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "unpause",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "status",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "totalRaised",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "issuer",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "withdrawTokens",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "depositProjectTokens",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "reject",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "emergencyWithdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "withdrawFunds",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "getPhaseCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getPhase",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "phaseId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "pricePerToken", type: "uint256" },
          { name: "allocation", type: "uint256" },
          { name: "sold", type: "uint256" },
          { name: "minContribution", type: "uint256" },
          { name: "maxContribution", type: "uint256" },
          { name: "startTime", type: "uint256" },
          { name: "endTime", type: "uint256" },
          { name: "whitelistOnly", type: "bool" },
        ],
      },
    ],
  },
  {
    name: "setOTCToken",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_otcToken", type: "address" }],
    outputs: [],
  },
  {
    name: "otcToken",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "SaleStatusChanged",
    type: "event",
    inputs: [
      { name: "newStatus", type: "uint8", indexed: false },
    ],
  },
  // View functions
  { name: "vault", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "fractionToken", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "issuer", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "factory", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { name: "saleMode", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { name: "feeBasisPoints", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
] as const;
